(SELECT CITY, LENGTH(CITY) AS length FROM STATION ORDER BY LENGTH(CITY) ASC , CITY ASC LIMIT 1 )
UNION ALL 
(SELECT CITY, LENGTH(CITY) AS length FROM STATION ORDER BY LENGTH(CITY) DSC , CITY ASC LIMIT 1 )