with long_cte as (
    select CITY, LENGTH(CITY) AS CL FROM STATION 
    ORDER BY CL DESC, CITY LIMIT 1
),
SHORT_CTE AS (
    SELECT CITY, LENGTH(CITY) AS CL FROM STATION 
    ORDER BY CL,CITY LIMIT 1
)
SELECT * FROM SHORT_CTE
UNION ALL
SELECT * FROM long_cte;
